### ISSUE TITLE
Sensitive data in repository

### ISSUE THREAD

**Issue by lyskov** [jferrie3/AbInitioVO-and-FastFloppyTail#1]
Dear @jferrie3 could you please remove login password pairs from you committed files, particularly from https://github.com/jferrie3/AbInitioVO-and-FastFloppyTail/blob/master/anaconda/lion.yml ? 
Thank,

**Comment by jferrie3** [comment]
Hi Sergey, 

Thank you so much for pointing this out. I was not aware that that info was in the yml file. I will take care of this now. 

Best, 
Jack

**Comment by lyskov** [comment]
Thank you! You probably aware of this but just in case: to really delete this data you will need to rewrite history (not just commit a new data on top), because otherwise old data will be accessible at [deleted]
Thanks,

**Comment by jferrie3** [comment]
The repository history has been rewritten to remove the file, however the link in your comment above links to a commit, that although it is no longer a part of the repository, still contains the file in question. If I close the issue will the resolve that problem? If not, how do you suggest I proceed. Again thank you for making me aware of this issue.

**Comment by jferrie3** [comment]
Alternatively I can remove the repository and upload a new one under an identical name.

**Comment by lyskov** [comment]
@jferrie3 thank you for taking care of this! I deleted the link and GitHub will clear cache eventually so i think we fine here, - i do not think deleting repository will be necessary.
Best,
